server:
  port: 8003

spring:
  application:
    name: service-payment

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/,http://localhost:7000/eureka/
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    filter-only-up-instances: true
    eureka-connection-idle-timeout-seconds: 30
    eureka-server-connect-timeout-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
#    prefer-ip-address: false
    instance-id: ${spring.cloud.client.ip-address}:${server.port}



mybatis:
  mapperLocations: classpath:/mapper/**
  typeAliasPackages: com.example.demo.magnus.entity
