spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MagnusLeona/magnus-config-server.git
          searchPaths: magnus-config-server
          username: magnusleona
          password: leonardo970915

eureka:
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://magnus.eureka:7000/eureka/, http://magnus.eureka:7001/eureka/
    registerWithEureka: true


server:
  port: 5000

