spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MagnusLeona/magnus-config-server.git
          searchPaths: repo
      label: main

eureka:
  client:
    serviceUrl:
      defaultZone: http://magnus.eureka:7000/eureka/, http://magnus.eureka:7001/eureka/



server:
  port: 5000

